name: Sync upstream

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync main branch with upstream
        run: gh repo sync "${{ github.repository }}" --branch main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out fork
        uses: actions/checkout@v6

      - name: Sync upstream tags
        run: |
          git remote add upstream https://github.com/eduardoribeirodev/filament-leaflet.git
          git fetch upstream --tags
          git push origin --tags